version: 1.0.{build}
branches:
  only:
  - MUSHclient
skip_tags: true
skip_branch_with_pr: true
skip_branch_with_pr: true
image: Visual Studio 2019
clone_depth: 1
environment:
  auth_token:
    secure: 91a7da5075cc3e55272885c1413e94f70e7b2556
build: off
