version: 1.0.{build}
branches:
  only:
  - MUSHclient
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
clone_depth: 1

install:
- ps: pushd C:\
- ps: Start-FileDownload 'https://github.com/fiendish/LuaJIT-build/releases/download/latest/lua51.dll'
- ps: Start-FileDownload 'https://github.com/fiendish/lua-llthreads2-build/releases/download/latest/llthreads2.dll'
- ps: Start-FileDownload 'https://github.com/fiendish/lua-openssl-build/releases/download/latest/openssl.dll'
- ps: Start-FileDownload 'https://github.com/nickgammon/mushclient/releases/download/latest_commit/MUSHclient.exe'
- ps: pushd C:\projects\dbummoclientpackage
- ps: |
      Move-Item C:\lua51.dll MUSHclient -force
      Move-Item C:\llthreads2.dll MUSHclient -force
      Move-Item C:\openssl.dll MUSHclient -force
      Move-Item C:\MUSHclient.exe MUSHclient -force
      $env:PACKAGE_VERSION=(Get-Content MUSHclient\DBUMMOPackageChanges.txt)[2].split()[0]
      7z a -tzip -mx=9 -mfb=257 DBU-MMO_MUSHclient_$($env:PACKAGE_VERSION)_no_install.zip MUSHclient
      Start-FileDownload 'https://raw.githubusercontent.com/Xinefus-Braska/dbummoclientpackage-installer-master/master/dbumush_installer.nsi'
      Start-FileDownload 'https://raw.githubusercontent.com/Xinefus-Braska/dbummoclientpackage-installer-master/master/get_version.nsi'
      Start-FileDownload 'https://raw.githubusercontent.com/Xinefus-Braska/dbummoclientpackage-installer-master/master/hello.rtf'
- cmd: '"C:\Program Files (x86)\NSIS\makensis.exe" dbumush_installer.nsi'
- ps: |
      function Insert-Content { param ( [String]$Path ); process { $( ,$_; Get-Content $Path -ea SilentlyContinue) | Out-File -encoding ASCII $Path } }
      "aard_req_novisuals_mode = true  -- this line added by the no-visuals installer`r`n" | Insert-Content .\MUSHclient\lua\aard_requirements.lua
      Move-Item .\MUSHclient\worlds\Aardwolf_no_visuals.mcl .\MUSHclient\worlds\Aardwolf.mcl -force
      $env:VIAPPOUT = 'OutFile "Aardwolf_MUSHclient_${PackageVersion}_no_visuals.exe"'
      (Get-Content aardmush_installer.nsi) | ForEach-Object { $_ -replace "OutFile.+" , "$env:VIAPPOUT" } | Set-Content aardmush_installer.nsi
- cmd: '"C:\Program Files (x86)\NSIS\makensis.exe" dbumush_installer.nsi'
- ps: |
      7z a -tzip -mx=9 -mfb=257 DBU-MMO_MUSHclient_$($env:PACKAGE_VERSION)_no_visuals_no_install.zip .\MUSHclient
      Get-ChildItem .\Aardwolf_MUSHclient_r*.exe -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      Get-ChildItem .\Aardwolf_MUSHclient_r*.zip -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      git checkout -- .

build: off
